output_dir: "results/evaluate"
seed: 10
task: "REDDIT"
dryrun: False
save_prompts: True
timeout: 0.0
store: True
task_config: 
    path: "predicted_synthethic_gpt4.jsonl"
    outpath: "eval_synthetic_gpt4.jsonl"
    eval: True
    decider: "model"
gen_model:
  name: "gpt-4"
  provider: "openai"
  args: {
    temperature: 0.1
  }
